#!/usr/bin/env python3
"""Render the link-preview card (Open Graph image) as HTML.

    python3 make_preview.py [market_watch_data.json] [/tmp/card.html]

Then screenshot it at 1200x630 — the recipe is in README.md. Kept out of
generator.py on purpose: the PNG needs headless Chrome, and the daily run on the
mini must not depend on a browser being present. Standard library only, like
everything else here.

The card carries the crash-risk composite with the composite's own date beside
it, not the report date. It is regenerated by hand rather than daily, so it will
sometimes be a few days behind the page — a dated snapshot is honest about that
in a way a bare number is not.
"""
import json, sys, os, html, datetime

data_path = sys.argv[1] if len(sys.argv) > 1 else "market_watch_data.json"
out_path  = sys.argv[2] if len(sys.argv) > 2 else "/tmp/card.html"

with open(data_path, encoding="utf-8") as f:
    D = json.load(f)

meta  = D["meta"]
crash = D["crash_risk"]
comp  = crash["composite"]
level = crash.get("level", "")
# The composite's own as-of, not the report date: they differ whenever the
# composite is carried rather than recomputed, and the page says so too.
c_as_of = (crash.get("composite_meta") or {}).get("as_of") or meta.get("report_date", "")
try:
    d = datetime.date.fromisoformat(c_as_of)
    c_label = d.strftime("%-d %b")
except ValueError:
    c_label = c_as_of

# Same thresholds as the gauge in template_v28.html.
gcol = "#f43f5e" if comp >= 70 else "#f59e0b" if comp >= 40 else "#10b981"

n_themes = len(D.get("investible_themes", []))
n_radar  = len(D.get("radar", []))

# --- the backdrop, from the same series the S&P tile renders ----------------
W, H, TOP, BOT = 1200, 258, 20, 0
hist = next((t.get("hist") or [] for t in D["state_of_play"]["tiles"]
             if "S&P" in t.get("lbl", "")), [])
art, lcol = "", "#10b981"
if len(hist) >= 8:
    lo, hi = min(hist), max(hist)
    rng = (hi - lo) or 1
    n = len(hist)
    pts = ["%s%.1f %.1f" % ("L" if i else "M", i * W / (n - 1),
                            TOP + (1 - (v - lo) / rng) * (H - TOP - BOT))
           for i, v in enumerate(hist)]
    line = "".join(pts)
    lcol = "#10b981" if hist[-1] >= hist[0] else "#f43f5e"
    art = ('<svg class="art" viewBox="0 0 %d %d" preserveAspectRatio="none">'
           '<defs><linearGradient id="f" x1="0" y1="0" x2="0" y2="1">'
           '<stop offset="0%%" stop-color="%s" stop-opacity=".20"/>'
           '<stop offset="100%%" stop-color="%s" stop-opacity="0"/></linearGradient></defs>'
           '<path d="%sL%d %dL0 %dZ" fill="url(#f)"/>'
           '<path d="%s" fill="none" stroke="%s" stroke-opacity=".62" stroke-width="2.4" '
           'stroke-linejoin="round" vector-effect="non-scaling-stroke"/></svg>'
           % (W, H, lcol, lcol, line, W, H, H, line, lcol))

CARD = """<!DOCTYPE html><html><head><meta charset="utf-8"><style>
*{{box-sizing:border-box;margin:0}}
html,body{{width:1200px;height:630px;overflow:hidden}}
body{{background:#09090b;color:#f4f4f5;position:relative;
  font:16px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Inter,Roboto,Helvetica,Arial,sans-serif}}
.art{{position:absolute;left:0;right:0;bottom:0;width:1200px;height:258px;
  -webkit-mask-image:linear-gradient(100deg,transparent 4%,rgba(0,0,0,.14) 26%,rgba(0,0,0,.55) 52%,#000 78%)}}
.in{{position:relative;z-index:2;padding:62px 72px 54px;height:100%;display:flex;flex-direction:column}}
.eb{{display:flex;align-items:center;gap:13px;font-size:20px;color:#a1a1aa}}
.lg{{width:38px;height:38px;border-radius:10px;background:linear-gradient(135deg,#60a5fa,#a78bfa);
  display:block;flex:0 0 auto}}
.eb b{{color:#f4f4f5;font-weight:600;letter-spacing:-.2px;font-size:22px}}
.eb .sep{{color:#3f3f46}}
.eb .up{{color:#71717a;font-size:19px}}
h1{{font-size:52px;line-height:1.16;font-weight:600;letter-spacing:-1.2px;margin:30px 0 18px;max-width:23ch}}
h1 em{{font-style:normal;background:linear-gradient(95deg,#60a5fa,#a78bfa);
  -webkit-background-clip:text;background-clip:text;color:transparent}}
p{{font-size:21px;line-height:1.55;color:#a1a1aa;max-width:38ch}}
.row{{margin-top:auto;display:flex;align-items:flex-end;gap:34px}}
.num{{font-size:82px;font-weight:600;line-height:.86;letter-spacing:-2px;color:{gcol};
  font-variant-numeric:tabular-nums}}
.lab{{font-size:14px;letter-spacing:1.4px;text-transform:uppercase;color:#71717a;margin-top:12px;
  white-space:nowrap}}
.lab b{{color:{gcol};font-weight:600}}
.pill{{border:1px solid #27272a;background:#131316;border-radius:999px;padding:9px 18px;
  font-size:17px;color:#a1a1aa;white-space:nowrap}}
.pill b{{color:#e4e4e7;font-weight:600}}
.pills{{display:flex;gap:10px;padding-bottom:6px}}
.disc{{font-size:14px;color:#3f3f46;margin-top:26px}}
</style></head><body>
{art}
<div class="in">
  <div class="eb"><span class="lg"></span><b>Market Watch</b>
    <span class="sep">/</span><span class="up">Analysis {report}</span></div>
  <h1>Markets, drivers and the themes <em>forming underneath them</em></h1>
  <p>Macro drivers and crash risk, alongside a register of investible themes tracked
     from first sighting on the radar through to played-out.</p>
  <div class="row">
    <div>
      <div class="num">{comp}</div>
      <div class="lab">Crash risk &middot; <b>{level}</b> &middot; as at {c_label}</div>
    </div>
    <div class="pills">
      <span class="pill"><b>{n_themes}</b> themes</span>
      <span class="pill"><b>{n_radar}</b> on the radar</span>
    </div>
  </div>
  <div class="disc">Research aid, not financial advice. No holdings, no positions, no sizing.</div>
</div></body></html>"""

with open(out_path, "w", encoding="utf-8") as f:
    f.write(CARD.format(art=art, gcol=gcol, comp=comp, level=html.escape(level).lower(),
                        c_label=html.escape(c_label), n_themes=n_themes, n_radar=n_radar,
                        report=html.escape(meta.get("report_date_long", ""))))
print("wrote", out_path, "- screenshot at 1200x630 to preview.png")
